package project.ui.admin.Reports;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Cursor;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;

import project.ui.admin.DashBoard.AdminSectionPage;

public class ReportDetailsPage extends AdminSectionPage {

    private static final String BG = "#D6F0F3";
    private static final String SURFACE = "#EEF9FA";
    private static final String SECONDARY = "#DFF3F5";

    private static final String BLUE = "#2563EB";
    private static final String GREEN = "#16A34A";

    private static final String HEADING = "#172033";
    private static final String TEXT = "#526274";
    private static final String BORDER = "#B8D4D9";

    private final ReportManagementPage.ReportData report;

    private final Runnable onBack;
    private final Runnable onPreview;

    public ReportDetailsPage(
            ReportManagementPage.ReportData report,
            Runnable onBack,
            Runnable onPreview
    ) {
        this.report = report;
        this.onBack = onBack;
        this.onPreview = onPreview;
    }

    @Override
    public VBox getView() {

        VBox root = new VBox(20);

        root.setPadding(
                new Insets(30, 32, 32, 32)
        );

        root.setStyle(
                "-fx-background-color: " + BG + ";"
        );

        Button backButton =
                new Button("← Back to Reports");

        styleOutlineButton(backButton);

        backButton.setOnAction(event -> {

            if (onBack != null) {
                onBack.run();
            }
        });

        Label title =
                new Label("Report Details");

        title.setTextFill(
                Color.web(HEADING)
        );

        title.setFont(
                Font.font(
                        "Arial",
                        FontWeight.BOLD,
                        32
                )
        );

        Label subtitle =
                new Label(
                        "View complete information about this RoadGuardian report."
                );

        subtitle.setTextFill(
                Color.web(TEXT)
        );

        subtitle.setFont(
                Font.font(
                        "Arial",
                        16
                )
        );

        VBox header =
                new VBox(5);

        header.getChildren().addAll(
                title,
                subtitle
        );

        VBox card =
                createDetailsCard();

        VBox.setVgrow(
                card,
                Priority.ALWAYS
        );

        root.getChildren().addAll(
                backButton,
                header,
                card
        );

        return root;
    }

    private VBox createDetailsCard() {

        VBox card =
                new VBox(18);

        card.setPadding(
                new Insets(24)
        );

        card.setStyle(
                "-fx-background-color: " + SURFACE + ";" +
                        "-fx-border-color: " + BORDER + ";" +
                        "-fx-border-radius: 14;" +
                        "-fx-background-radius: 14;"
        );

        Label reportName =
                new Label(
                        report.getName()
                );

        reportName.setTextFill(
                Color.web(HEADING)
        );

        reportName.setFont(
                Font.font(
                        "Arial",
                        FontWeight.BOLD,
                        24
                )
        );

        HBox firstRow =
                new HBox(14);

        VBox id =
                createInfoBox(
                        "REPORT ID",
                        report.getId()
                );

        VBox type =
                createInfoBox(
                        "REPORT TYPE",
                        report.getType()
                );

        HBox.setHgrow(
                id,
                Priority.ALWAYS
        );

        HBox.setHgrow(
                type,
                Priority.ALWAYS
        );

        firstRow.getChildren().addAll(
                id,
                type
        );

        HBox secondRow =
                new HBox(14);

        VBox generatedBy =
                createInfoBox(
                        "GENERATED BY",
                        report.getGeneratedBy()
                );

        VBox date =
                createInfoBox(
                        "GENERATED DATE",
                        report.getDate()
                );

        VBox records =
                createInfoBox(
                        "TOTAL RECORDS",
                        report.getRecords()
                );

        HBox.setHgrow(
                generatedBy,
                Priority.ALWAYS
        );

        HBox.setHgrow(
                date,
                Priority.ALWAYS
        );

        HBox.setHgrow(
                records,
                Priority.ALWAYS
        );

        secondRow.getChildren().addAll(
                generatedBy,
                date,
                records
        );

        Label summaryTitle =
                new Label("Report Summary");

        summaryTitle.setTextFill(
                Color.web(HEADING)
        );

        summaryTitle.setFont(
                Font.font(
                        "Arial",
                        FontWeight.BOLD,
                        19
                )
        );

        Label summary =
                new Label(
                        "This is the " +
                                report.getType() +
                                " report generated by " +
                                report.getGeneratedBy() +
                                ". The report contains " +
                                report.getRecords() +
                                " records."
                );

        summary.setWrapText(true);

        summary.setTextFill(
                Color.web(TEXT)
        );

        summary.setFont(
                Font.font(
                        "Arial",
                        14
                )
        );

        HBox actions =
                new HBox();

        actions.setAlignment(
                Pos.CENTER_RIGHT
        );

        Button previewButton =
                new Button(
                        "Preview Report"
                );

        styleGreenButton(
                previewButton
        );

        previewButton.setOnAction(event -> {

            if (onPreview != null) {
                onPreview.run();
            }
        });

        actions.getChildren().add(
                previewButton
        );

        card.getChildren().addAll(
                reportName,
                firstRow,
                secondRow,
                summaryTitle,
                summary,
                actions
        );

        ScrollPane scroll =
                new ScrollPane(card);

        scroll.setFitToWidth(true);

        scroll.setHbarPolicy(
                ScrollPane.ScrollBarPolicy.NEVER
        );

        scroll.setStyle(
                "-fx-background-color: transparent;" +
                        "-fx-background: transparent;"
        );

        VBox wrapper =
                new VBox(scroll);

        VBox.setVgrow(
                scroll,
                Priority.ALWAYS
        );

        return wrapper;
    }

    private VBox createInfoBox(
            String title,
            String value
    ) {

        VBox box =
                new VBox(6);

        box.setPadding(
                new Insets(15)
        );

        box.setStyle(
                "-fx-background-color: " + SECONDARY + ";" +
                        "-fx-border-color: " + BORDER + ";" +
                        "-fx-border-radius: 9;" +
                        "-fx-background-radius: 9;"
        );

        Label titleLabel =
                new Label(title);

        titleLabel.setTextFill(
                Color.web(TEXT)
        );

        titleLabel.setFont(
                Font.font(
                        "Arial",
                        FontWeight.BOLD,
                        11
                )
        );

        Label valueLabel =
                new Label(
                        value == null || value.isBlank()
                                ? "-"
                                : value
                );

        valueLabel.setTextFill(
                Color.web(HEADING)
        );

        valueLabel.setFont(
                Font.font(
                        "Arial",
                        FontWeight.BOLD,
                        15
                )
        );

        valueLabel.setWrapText(true);

        box.getChildren().addAll(
                titleLabel,
                valueLabel
        );

        return box;
    }

    private void styleOutlineButton(
            Button button
    ) {

        button.setTextFill(
                Color.web(BLUE)
        );

        button.setFont(
                Font.font(
                        "Arial",
                        FontWeight.BOLD,
                        14
                )
        );

        button.setPadding(
                new Insets(10, 18, 10, 18)
        );

        button.setCursor(Cursor.HAND);

        button.setStyle(
                "-fx-background-color: " + SURFACE + ";" +
                        "-fx-border-color: " + BLUE + ";" +
                        "-fx-border-radius: 8;" +
                        "-fx-background-radius: 8;"
        );
    }

    private void styleGreenButton(
            Button button
    ) {

        button.setTextFill(
                Color.WHITE
        );

        button.setFont(
                Font.font(
                        "Arial",
                        FontWeight.BOLD,
                        14
                )
        );

        button.setPadding(
                new Insets(10, 18, 10, 18)
        );

        button.setCursor(Cursor.HAND);

        button.setStyle(
                "-fx-background-color: " + GREEN + ";" +
                        "-fx-background-radius: 8;"
        );
    }
}